name: Keep AIdsorb-online awake

on:
  schedule:
    - cron: '28 19 * * 2' # Runs 21:40 (UTC, every Monday)

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a dummy commit
      run: |
        date > last_awake.txt
        git add last_awake.txt
        git commit -m "Keep AIdsorb-online awake: $(date)"
        git push
