name: Keep AIdsorb-online awake

on: workflow_dispatch

permissions:
  contents: write

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

  my-job:
    runs-on: ubuntu-latest
    needs:
      - keep-awake
    steps:
      - run: echo $(ls)
      - run: echo $(pwd)
      - run: echo $(python -m version)
