name: Foo

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print the tag
        run: echo "Deploying tag: ${{ github.event.inputs.tags }}"
