name: GitHub action demo
run-name: I am running the demo

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo hello world
      - name: commit
        run: |
          git ls-files
