name: Keep AIdsorb-online awake

on: workflow_dispatch

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configurate git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Make a dummy commit
      run: |
        date > last_awake.txt
        git add last_awake.txt
        git commit -m "Keep AIdsorb-online awake: $(date)"
        git push
